### PR TITLE
Weekyear related functions

### LINKED ISSUE #116: Problem with formatters list?
I'm putting what I suspect is too much info here, but I really have NO idea where the problem is coming from.

In short, I can't view the list of formatters with show-formatters, and I also can explicitly define a working formatter that's (I think) identical to the :basic-date-time formatter, but coerce/from-string won't work on an example date. This makes me think there's some basic problem with the list of formatters.

Here's the packages in :dependencies in my project.clj for leiningen (on windows, running lein figwheel from powershell):

```
                [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [org.clojure/core.async  "0.3.443"]
                 [rum "0.10.8"]
                 [cljs-http "0.1.43"]
                 [com.andrewmcveigh/cljs-time "0.5.0"]
                 ]
```

I include format in my ns declaration
```
(ns scrape-n-mail.core                                            
    (:require [rum.core :as rum]                                  
              [cljs-http.client :as http]                         
              [clojure.string :as s]                              
              [cljs-time.format :as fmt]                          
              [cljs.core.async :refer [<!]])                      
    (:require-macros [cljs.core.async.macros :refer [go go-loop]])
    )                                                             
```

I'm running this directly at the figwheel repl:

```
=> (fmt/show-formatters)
:basic-date                             20171105

:basic-date-time                        20171105T014406.842Z

:basic-date-time-no-ms                  20171105T014406Z

:basic-ordinal-date                     2017005

:basic-ordinal-date-time                2017005T014406.842Z

:basic-ordinal-date-time-no-ms          2017005T014406Z

:basic-t-time                           T014406.842Z

:basic-t-time-no-ms                     T014406Z

:basic-time                             014406.842Z

:basic-time-no-ms                       014406Z

#object[Error Error: No matching clause: e]
   cljs_time$internal$unparse$lookup (jar:file:/C:/Users/davcl/.m2/repository/com/andrewmcveigh/cljs-time/0.5.0/cljs-time-0.5.0.jar!/cljs_time/internal/unparse.cljs:131:5)
   cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 (jar:file:/C:/Users/davcl/.m2/repository/org/clojure/clojurescript/1.9.229/clojurescript-1.9.229.jar!/cljs/core.cljs:19391:3)
   Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 (jar:file:/C:/Users/davcl/.m2/repository/org/clojure/clojurescript/1.9.229/clojurescript-1.9.229.jar!/cljs/core.cljs:2358:29)
   Function.cljs.core.mapv.cljs$core$IFn$_invoke$arity$2 (jar:file:/C:/Users/davcl/.m2/repository/org/clojure/clojurescript/1.9.229/clojurescript-1.9.229.jar!/cljs/core.cljs:4752:11)
   cljs.core/mapv (jar:file:/C:/Users/davcl/.m2/repository/org/clojure/clojurescript/1.9.229/clojurescript-1.9.229.jar!/cljs/core.cljs:4745:1)
   cljs-time.internal.unparse/unparse (jar:file:/C:/Users/davcl/.m2/repository/com/andrewmcveigh/cljs-time/0.5.0/cljs-time-0.5.0.jar!/cljs_time/internal/unparse.cljs:204:19)
   cljs_time$format$unparse (jar:file:/C:/Users/davcl/.m2/repository/com/andrewmcveigh/cljs-time/0.5.0/cljs-time-0.5.0.jar!/cljs_time/format.cljs:249:4)
n
```

Any ideas?

### PR DESCRIPTION
**Pull request by shen-tian**
Does correct unparsing of "e" (day of week)

Fixes #116 

WIP

### CODE REVIEW

**Comment by shen-tian** [comment]
Confirmed that this fixes #98 

Though that underlying bug was probably fixed a while ago.

Main thing to do here to see how parsing of weekyears work.

**Comment by shen-tian** [comment]
Done for now:

- Implements parsing and unparsing of the day of week field ("e")
- Implements the `week-year` fn in `core` per [this PR](https://github.com/clj-time/clj-time/pull/240) in `clj-time`, (also me).

File: src/cljs_time/core.cljs [hunk 1]
```diff
@@ -187,6 +188,17 @@ expected."}
       (not= dayo dayother) (- dayo dayother)
       :else 0)))
 
+(defn get-week-year
```
Comment (andrewmcveigh) [inline src/cljs_time/core.cljs]: Could this go in `cljs-time.internal.core`? I'd rather not expose 2 new names doing the same thing.

File: src/cljs_time/internal/unparse.cljs [hunk 2]
```diff
@@ -50,8 +50,18 @@
...
+  ([min max]
+   (fn [s d]
+     (let [raw-day-of-week (.getDay d)
+           day-of-week (if (= raw-day-of-week 0)
+                         7 raw-day-of-week)]
+       (unparse-period s d day-of-week min max)))))
+
 (defn unparse-day-of-year
-  ([min] (unparse-day min min))
+  ([min] (unparse-day min min)) ;; <- this right?
```
Comment (andrewmcveigh) [inline src/cljs_time/internal/unparse.cljs]: It is right, but I can see how it looks a bit weird 😉 

Maybe the 1-ary versions of these functions is a bit superfluous?

File: src/cljs_time/internal/parse.cljs [hunk 3]
```diff
@@ -285,20 +291,39 @@
...
         century (- year (mod year 100))
         years (or years default-year 0)
         years (cond-> years
                 (< years (mod (+ pivot 50) 100))
-                (+ century))
+                (+ century))]
+    years))
+
+(defn week-date->gregorian
+  [{:keys [weekyear weekyear-week day-of-week] :as date-map}]
```
Comment (andrewmcveigh) [inline src/cljs_time/internal/parse.cljs]: I'm a bit concerned about if the case where someone uses a formatter that includes, E.G., `yyyy` and `xxxxww`.

It's kind of a user-error, but would probably lead them to many WTF!?s when the weekyear is overriding year.

Do you think we should do some validation? There is already a date validation fn at [1], maybe that should be extended to check that both year & weekyear are not set at the same time?

[1]
https://github.com/andrewmcveigh/cljs-time/blob/d31ccf1a656db6d45caa8c3c3fb355de9185dc79/src/cljs_time/internal/core.cljs#L38

Comment (shen-tian) [reply src/cljs_time/internal/parse.cljs]: Will think a bit about what combinations are valid, but yes, adding to `valid-date?` is probably right.

File: src/cljs_time/core.cljs (hunk 1 above)
Comment (shen-tian) [reply src/cljs_time/core.cljs]: Can do.

File: src/cljs_time/internal/parse.cljs (hunk 3 above)
Comment (shen-tian) [reply src/cljs_time/internal/parse.cljs]: Added to `validate-date?`, where you can mix between `years months days` and `weekyears weekyear-weeks day-of-week`. This catches the error a bit later than creating the `xxxx-yyyy-ww` formatter, but I'm not sure whether an `yyyy-yy-yyyy` formatter is valid either?

File: src/cljs_time/internal/unparse.cljs (hunk 2 above)
Comment (shen-tian) [reply src/cljs_time/internal/unparse.cljs]: What caught my eye was that `unparse-day-of-year` calls `unparse-day`. Turns out `unparse-day-of-year` is not even used.

The bigger issue is that parsing and unparsing of `day-of-year` is actually wrong. (i.e. the "D" fields). This is currently matched to day-of-month ("d"). 

Happy to fix that in another PR though.

Comment (andrewmcveigh) [reply src/cljs_time/internal/unparse.cljs]: Hah, interesting. Seems like an oversight when I rewrote the parser.

File: src/cljs_time/internal/parse.cljs (hunk 3 above)
Comment (andrewmcveigh) [reply src/cljs_time/internal/parse.cljs]: Yeah, you're right actually. There isn't much formatter validation. And this would belong in formatter validation. (rather than data validation)

It's better here than nowhere at least.

File: src/cljs_time/internal/unparse.cljs (hunk 2 above)
Comment (andrewmcveigh) [reply src/cljs_time/internal/unparse.cljs]: You mind just getting rid of this comment and I'll get this merged?

Comment (shen-tian) [reply src/cljs_time/internal/unparse.cljs]: Done

**Comment by andrewmcveigh** [comment]
This is really great, thanks very much!
